### PR TITLE
feat: reset password token

### PR DESCRIPTION
**Pull request by Ofektom**
### Description
Create a backend endpoint that allows users to reset their password using a secure token received via email. The endpoint should validate the token, accept the new password, and update the user’s credentials in the database.

### Changes made
- Created POST request endpoint to reset the password with a new password
- Created resetPassword method in the user service implementation class for the business logic

#### Endpoint
`/api/v1/auth/reset-password/{token}`

#### Request Body
```json
{
    "new_password":"Password321"
}
``` 
#### Response
"Password Reset Successful"

### Linked issue
The feature is linke to the [issue](https://github.com/hngprojects/hng_boilerplate_java_web/issues/626)

### CODE REVIEW

**Comment by Ofektom** [comment]
@Am0du @Adewale66 @Fifetoyi please review

**Review by Adewale66 — DISMISSED** [review]
LGTM @Am0du

**Comment by Ofektom** [comment]
@lurldgbodex @gurumarv @Fifetoyi please review and merge

**Comment by lurldgbodex** [comment]
you have conflict

**Comment by Ofektom** [comment]
Conflict resolved @Am0du

**Comment by Ofektom** [comment]
@lurldgbodex resolved

**Review by Fifetoyi — APPROVED** [review]
lgtm

**Pull request merged**
