### PR TITLE
[Feat]: forgot password

### PR DESCRIPTION
**Pull request by Ofektom**
### Description
Implement a backend endpoint that allows users to initiate a password reset process by providing their registered email. The endpoint should generate a secure token and send it to the user's email for further verification.

### Changes made
- Created POST request endpoint for forgot password
- Created forgotPassword method to send email to the user
- Created createPasswordResetTokenForUser method to generate token for forgot password
- Created test class to test the forgot password method

#### Endpoint:
`/api/v1/auth/forgot-password`

#### Request Body
```json
{
    "email": "blesseddoe@gmail.com"
}
```

#### Response
"Forgot password email sent successfully"

### Linked Issue:
This ticket is linked to the [issue](https://github.com/hngprojects/hng_boilerplate_java_web/issues/619)

### CODE REVIEW

**Comment by Ofektom** [comment]
@Amodu, @Adewale66 please review

**Comment by Adewale66** [comment]
Your migration file is on 43. What about 41?

**Comment by Ofektom** [comment]
> Your migration file is on 43. What about 41?

There are other PRs using 41 and 42

**Comment by Adewale66** [comment]
Please adjust it because if this pr gets merged first it'll cause a migration error when the other ones get merged, the pipeline won't throw any migration error for them since it's running from scratch

**Review by Adewale66 — DISMISSED** [review]
LGTM @Am0du @lurldgbodex

**Comment by Ofektom** [comment]
@Am0du please, I've resolved the conflict

**Comment by Adewale66** [comment]
Migration file conflict @Ofektom

**Review by Adewale66 — APPROVED** [review]
LGTM @Am0du

**Comment by Ofektom** [comment]
@Am0du I have resolved conflict again and the body has been adjusted to the required

**Pull request merged**
