### PR TITLE
feat: magic link mail

### PR DESCRIPTION
**Pull request by Ofektom**
### Description
Develop a backend endpoint that generates and sends a magic link to a user’s email for quick login without a password. The magic link should contain a secure token that, when clicked, logs the user into their account.

#### Endpoint
`/api/v1/auth/magic-link`

#### Request Body
```json
{
    "email": "okpohot@gmail.com"
}
``` 
#### Response
"Magic link sent successfully! Go to your email to login"

### Related Issue
The feature is related to the [issue](https://github.com/hngprojects/hng_boilerplate_java_web/issues/633)

### CODE REVIEW

**Comment by Ofektom** [comment]
@Am0du @Adewale66 please review this

**Comment by Ofektom** [comment]
The PR includes some fixes in the response body and the super admin password as requested by a developer for urgent use

**Review by Fifetoyi — DISMISSED** [review]
lgtm

**Comment by Am0du** [comment]
@Ofektom please you have conflicts

**Comment by Ofektom** [comment]
@Am0du I have resolved it

**Comment by lurldgbodex** [comment]
you still have conflict

**Comment by Ofektom** [comment]
@lurldgbodex resolved

**Comment by Ofektom** [comment]
@Fifetoyi please check

**Review by Fifetoyi — APPROVED** [review]
lgtm

**Pull request merged**
