### PR TITLE
feat: user-login

### PR DESCRIPTION
**Pull request by Ofektom**
####  Using Postman
i. Open Postman.

ii. Create a new POST request.

iii. Enter the endpoint URL: http://localhost:8080/api/v1/auth/login

iv. Set the request body type to raw and select JSON from the dropdown.

v. Paste the following JSON into the body:
```
{
  "email": "johndoe@example.com",
  "password": "Johndo3!"
}
```
vi. Click on the `Send` button.

#### **Success Response**

- **Status Code**: `200 OK`
- **Response Body**:
```json

{
  "status_code": 200,
  "message": "Login Successful!",
  "data": {
    "token": "some-token",
    "user": {
      "id": "some-user-id",
      "first_name": "John",
      "last_name": "Doe",
      "email": "johndoe@example.com",
      "created_at": "2024-07-19T20:28:34.399829"
    }
  }
}

### CODE REVIEW

**Comment by Am0du** [comment]
@Ofektom please a proper pr is adviced

**Comment by Ofektom** [comment]
please what is missing in the pr, is it the description or the message is not properly written?

**Comment by Am0du** [comment]
@Ofektom Yes

**Comment by Ofektom** [comment]
@Am0du is this okay

**Comment by Am0du** [comment]
Yes

**Comment by Am0du** [comment]
LGTM

**Review by Am0du — APPROVED** [review]

**Review by lurldgbodex — APPROVED** [review]

**Pull request merged**
