### PR TITLE
fix: create default organisation for signup user

### PR DESCRIPTION
**Pull request by Ofektom**
### Description
When a new user signs up, they should be automatically assigned to a default organisation with name (first_name's Organisation). This ensures that each user is part of an organisation by default, allowing them to immediately start using features that require organisational context.

### Key changes:
- Created a private method to split the full name of the user saved in the database to first name and last name
- Created a private method to create default organisation with the name "fisrt_name's Organisation" in the user service implementation class
- Called the createDefaultOrganisation method in the registerUser method to create the registerUser method to create an organisation for the user while signing up.

#### Endpoint: 
`/api/v1/auth/register`

#### Request Body:
```json
{
    "first_name": "Blessed",
	"last_name": "Doe",
	"email": "blesseddoe@example.com",
	"password": "password123"
}
```

#### Response Body

```json
{
    "status_code": 201,
    "message": "Registration Successful!",
    "data": {
        "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJva3BvaG90QGdtYWlsLmNvbSIsImlhdCI6MTcyNDQ4NjI5NCwiZXhwIjoxNzI0NDg5ODk0fQ.5ZaMingshJhjwrqpjFu5Q0zUrwoYCpcnfA6c6oTcxtyzA45MiG0AdVc8kqpYP1SHkBD3x3nNHn88bbYjc7O3wQ",
        "user": {
            "id": "988a0b83-6bd4-4c50-b675-b45c343c2ec4",
            "first_name": "Blessed",
            "last_name": "Doe",
            "email": "blesseddoe@example.com",
            "role": null,
            "imr_url": null,
            "organisations": [
                {
                    "id": "1d658df9-9e2a-4c80-8d3d-3a6ff47469d7",
                    "name": "Blessed's Organisation",
                    "description": "Default organisation for Blessed",
                    "slug": null,
                    "email": null,
                    "industry": null,
                    "type": null,
                    "country": null,
                    "address": null,
                    "state": null,
                    "createdAt": "2024-08-24T08:58:13.745934",
                    "updatedAt": "2024-08-24T08:58:13.745976",
                    "owner": "988a0b83-6bd4-4c50-b675-b45c343c2ec4"
                }
            ],
            "created_at": "2024-08-24T08:58:13.666572"
        }
    }
}
```
### Relates Issue
Refer to the [issue](https://github.com/hngprojects/hng_boilerplate_java_web/issues/616)

### CODE REVIEW

**Comment by Ofektom** [comment]
@Am0du @lurldgbodex  please review this

**Review by Am0du — DISMISSED** [review]

**Review by Adewale66 — DISMISSED** [review]
LGTM @Am0du

**Comment by Ofektom** [comment]
@Am0du @Adewale66 Conflict resolved

**Comment by Adewale66** [comment]
LGTM @Am0du

**Comment by Am0du** [comment]
@Ofektom Please use the specified body so i can merge this

**Review by Am0du — APPROVED** [review]

**Pull request merged**
